import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import api from '../../api';
import { useAuth } from '../../context/AuthContext';
import { getImageUrl } from '../../utils/urls';
import { FiSave, FiArrowLeft } from 'react-icons/fi';

import { useCategories } from '../../context/CategoryContext';

const WEIGHT_OPTIONS = [
    { value: 400, label: '400 г (Бенто)' },
    { value: 500, label: '500 г' },
    { value: 600, label: '600 г' },
    { value: 800, label: '800 г' },
    { value: 1000, label: '1 кг' },
    { value: 1500, label: '1.5 кг' },
    { value: 2000, label: '2 кг' },
    { value: 2500, label: '2.5 кг' },
    { value: 3000, label: '3 кг' },
    { value: 4000, label: '4 кг' },
    { value: 5000, label: '5 кг' }
];

export default function ProductEdit() {
    const { id } = useParams();
    const navigate = useNavigate();
    const { token } = useAuth();
    const { categories } = useCategories();
    const isNew = !id || id === 'new';
    const [loading, setLoading] = useState(!isNew);
    const [activeTab, setActiveTab] = useState('content'); // 'content' or 'seo'

    const [formData, setFormData] = useState({
        name: '',
        slug: '',
        price: '',
        description: '',
        weight: '',
        image_url: '',
        image_url_2: '',
        image_url_3: '',
        is_available: true,
        is_deleted: false,
        variants: [],
        specifications_json: [],
        faqs_json: [],
        // SEO
        meta_title: '',
        meta_description: '',
        h1_heading: '',
        meta_keywords: '',
        canonical_url: ''
    });

    useEffect(() => {
        if (isNew) {
            setLoading(false);
            return;
        }

        const fetchProduct = async () => {
            try {
                const response = await api.get(`/products/${id}`);
                const data = response.data;
                const isBriket = data.category === 'brikety';
                const nameLower = (data.name || '').toLowerCase();

                let autoSeoTitle = data.seo_title || data.meta_title || '';
                let autoSeoDesc = data.seo_description || data.meta_description || '';
                let autoSeoH1 = data.seo_h1 || data.h1_heading || '';

                let wasAutoGenerated = false;

                if (isBriket) {
                    if (!autoSeoTitle) {
                        wasAutoGenerated = true;
                        if (nameLower.includes('ruf') && nameLower.includes('дуб')) {
                            autoSeoTitle = `Купити брикети RUF дуб у Києві — доставка | КиївДрова`;
                        } else if (nameLower.includes('pini kay') || nameLower.includes('піні кей')) {
                            autoSeoTitle = `Купити брикети Pini Kay у Києві — євродрова | КиївДрова`;
                        } else if (nameLower.includes('nestro') || nameLower.includes('нестро')) {
                            autoSeoTitle = `Купити брикети Nestro у Києві — циліндричні брикети | КиївДрова`;
                        } else if (nameLower.includes('торф') || nameLower.includes('torf')) {
                            autoSeoTitle = `Купити торфобрикети у Києві — економне опалення | КиївДрова`;
                        } else {
                            autoSeoTitle = `Купити ${data.name.toLowerCase()} у Києві — доставка | КиївДрова`;
                        }
                    }

                    if (!autoSeoDesc) {
                        wasAutoGenerated = true;
                        if (nameLower.includes('ruf') && nameLower.includes('дуб')) {
                            autoSeoDesc = `Якісні паливні брикети RUF з дубової тирси. Висока тепловіддача та мінімум попелу. Доставка по Києву та області.`;
                        } else {
                            autoSeoDesc = `Замовляйте ${data.name.toLowerCase()} з швидкою доставкою по Києву та області.`;
                        }
                    }

                    if (!autoSeoH1) {
                        wasAutoGenerated = true;
                        if (nameLower.includes('ruf') && nameLower.includes('дуб')) {
                            autoSeoH1 = `Брикети RUF (дуб) — паливні брикети для котлів та печей`;
                        } else if (nameLower.includes('pini kay') || nameLower.includes('піні кей')) {
                            autoSeoH1 = `Брикети Pini Kay — євродрова з підвищеною тепловіддачею`;
                        } else {
                            autoSeoH1 = data.name;
                        }
                    }
                }

                const ogT = data.og_title || autoSeoTitle;
                const ogD = data.og_description || autoSeoDesc;

                // Generate default specifications if empty
                let defaultSpecs = data.specifications_json || [];
                if (!defaultSpecs || defaultSpecs.length === 0) {
                    defaultSpecs = [
                        { name: 'Порода', value: data.ingredients || (nameLower.includes('дуб') ? 'Дуб' : (nameLower.includes('сосн') ? 'Сосна' : (nameLower.includes('граб') ? 'Граб' : (data.category === 'brikety' ? 'Деревна тирса' : 'Тверді породи')))) },
                        { name: 'Тип', value: data.category === 'drova' ? 'Колоті, Ящик' : (data.category === 'brikety' ? 'Пресовані' : 'Сипуче') },
                        data.category === 'brikety'
                            ? { name: 'Форма брикетів', value: nameLower.includes('ruf') ? 'Прямокутні пресовані' : nameLower.includes('pini') ? 'Восьмигранні з отвором' : nameLower.includes('nestro') ? 'Циліндричні' : nameLower.includes('пелет') ? 'Гранули 6-8 мм' : 'Пресований торф' }
                            : { name: 'Довжина полін', value: data.category === 'drova' ? '30-40 см' : '—' },
                        { name: 'Фасування', value: data.category === 'drova' ? 'Складометр' : 'У пакуваннях / піддонах' },
                        { name: 'Вологість', value: data.category === 'drova' ? 'Природна (До 25%)' : (data.category === 'brikety' ? '8-10%' : 'До 8%') },
                        { name: 'Доставка', value: 'По Києву та області' }
                    ];
                }

                // Generate default FAQs if empty
                let defaultFaqs = data.faqs_json || [];
                if (!defaultFaqs || defaultFaqs.length === 0) {
                    if (data.category === 'brikety') {
                        defaultFaqs = [
                            { q: `Які брикети краще для опалення?`, a: `Для максимальної тепловіддачі та тривалого горіння найкраще підходять дубові брикети RUF або Pini Kay. Якщо у вас котел тривалого горіння, Nestro також стануть чудовим вибором. Для автоматичних котлів використовують пелети.` },
                            { q: `Скільки горять паливні брикети?`, a: `Залежно від типу котла та подачі кисню, брикети горять від 2 до 4 годин, після чого можуть тліти ще кілька годин, підтримуючи високу температуру.` },
                            { q: `Чим брикети відрізняються від дров?`, a: `Брикети мають вищу щільність і набагато нижчу вологість (до 10%), тому вони віддають більше тепла. Крім того, вони займають менше місця при зберіганні та залишають значно менше попелу.` },
                            { q: `Чи підходять брикети для камінів?`, a: `Так, особливо брикети RUF та Pini Kay. Вони горять рівним полум'ям, не іскрять і не виділяють зайвого диму, що робить їх ідеальними для відкритих та закритих камінів.` },
                            { q: `Як замовити брикети з доставкою по Києву?`, a: `Оберіть потрібний тип та кількість брикетів на сайті, натисніть "Замовити", і наш менеджер зв'яжеться з вами для уточнення деталей доставки. Ми доставляємо власною технікою протягом 24 годин.` }
                        ];
                    } else {
                        defaultFaqs = [
                            { q: `Які дрова краще для опалення?`, a: `${data.ingredients || 'Дубові'} дрова вважаються одними з найкращих для опалення завдяки високій щільності деревини та тривалому горінню. Вони дають стабільний жар і підходять для твердопаливних котлів, печей та камінів.` },
                            { q: `Яка довжина полін у дров?`, a: `Стандартна довжина полін — 30-40 см. Це оптимальний розмір для більшості побутових котлів та печей.` },
                            { q: `Скільки дров потрібно на зиму?`, a: `Для опалення будинку площею 100 м² на один опалювальний сезон потрібно приблизно 8-12 складометрів дров, залежно від утеплення та типу котла.` },
                            { q: `Як відбувається доставка?`, a: `Доставка дров здійснюється власним автопарком: ГАЗель (2 склм), ЗІЛ (5 склм), КАМАЗ (10 склм). Також доступні гідроборт та кран-маніпулятор. Доставка по Києву та області протягом 24 годин.` },
                            { q: `Який об'єм складометра?`, a: `Складометр — це щільно укладене паливо в об'ємі 1×1×1 метр. Ми завжди гарантуємо чесний об'єм при завантаженні автомобіля.` }
                        ];
                    }
                }

                // Generate default Delivery Info if empty
                let defaultDelivery = data.delivery_info_json || {};
                if (!defaultDelivery || Object.keys(defaultDelivery).length === 0) {
                    defaultDelivery = {
                        location: 'Доставка по Києву та області',
                        time: '1 день',
                        price: 'Індивідуальна вартість доставки буде розрахована після вашого запиту',
                        min_order: data.category === 'drova' ? '1 складометр' : '',
                        fleet: data.category === 'drova' ? 'ГАЗель, ЗІЛ, КАМАЗ' : '',
                        special: data.category === 'drova' ? 'гідроборт, кран-маніпулятор' : ''
                    };
                }

                // Generate default Order Steps if empty
                let defaultOrderSteps = data.order_steps_json || [];
                if (!defaultOrderSteps || defaultOrderSteps.length === 0) {
                    defaultOrderSteps = [
                        { step: `Оберіть потрібний обсяг ${data.category === 'brikety' ? 'брикетів' : data.category === 'vugillya' ? 'вугілля' : 'дров'}` },
                        { step: `Натисніть кнопку "Замовити"` },
                        { step: `Ми зв'яжемося для підтвердження доставки` }
                    ];
                }

                setFormData({
                    ...data,
                    // Ensure fields are not null for inputs
                    slug: data.slug || '',
                    description: data.description || '',
                    weight: data.weight || '',
                    category: data.category || '',
                    image_url: data.image_url || '',
                    image_url_2: data.image_url_2 || '',
                    image_url_3: data.image_url_3 || '',
                    variants: data.variants || [],
                    specifications_json: defaultSpecs,
                    faqs_json: defaultFaqs,
                    delivery_info_json: defaultDelivery,
                    order_steps_json: defaultOrderSteps,
                    seo_title: autoSeoTitle,
                    seo_description: autoSeoDesc,
                    seo_h1: autoSeoH1,
                    og_title: ogT,
                    og_description: ogD,
                    canonical_url: data.canonical_url || ''
                });

                // Store in admin database silently if automatically generated on load
                if (wasAutoGenerated) {
                    api.patch(`/products/${id}`, {
                        seo_title: autoSeoTitle,
                        seo_description: autoSeoDesc,
                        seo_h1: autoSeoH1,
                        meta_title: autoSeoTitle,
                        meta_description: autoSeoDesc,
                        h1_heading: autoSeoH1,
                        og_title: ogT,
                        og_description: ogD
                    }, { headers: { Authorization: `Bearer ${token}` } }).catch(e => console.error("Silent auto-save failed", e));
                }

            } catch (error) {
                console.error("Failed to fetch product", error);
            } finally {
                setLoading(false);
            }
        };
        fetchProduct();
    }, [id, isNew]);

    const handleChange = (e) => {
        const { name, value, type, checked } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: type === 'checkbox' ? checked : value
        }));
    };

    const addVariant = () => {
        setFormData(prev => ({ ...prev, variants: [...prev.variants, { name: '', price: '' }] }));
    };

    const updateVariant = (index, field, value) => {
        const newVariants = [...formData.variants];
        newVariants[index][field] = value;
        setFormData(prev => ({ ...prev, variants: newVariants }));
    };

    const removeVariant = (index) => {
        setFormData(prev => ({ ...prev, variants: prev.variants.filter((_, i) => i !== index) }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            // Convert numbers to correct types and cleanup variants
            const cleanedVariants = formData.variants
                .filter(v => v.name.trim() !== '')
                .map(v => ({ name: v.name.trim(), price: parseFloat(v.price) || 0 }));

            const cleanedSpecs = (formData.specifications_json || []).filter(s => s.name.trim() !== '' && s.value.trim() !== '');
            const cleanedFaqs = (formData.faqs_json || []).filter(f => f.q.trim() !== '' && f.a.trim() !== '');
            const cleanedOrderSteps = (formData.order_steps_json || []).filter(s => s.step && s.step.trim() !== '');

            const dataToSave = {
                ...formData,
                price: parseFloat(formData.price),
                weight: formData.weight ? parseFloat(formData.weight) : null,
                variants: cleanedVariants.length > 0 ? cleanedVariants : null,
                specifications_json: cleanedSpecs.length > 0 ? cleanedSpecs : null,
                faqs_json: cleanedFaqs.length > 0 ? cleanedFaqs : null,
                delivery_info_json: Object.keys(formData.delivery_info_json || {}).some(k => formData.delivery_info_json[k]?.trim()) ? formData.delivery_info_json : null,
                order_steps_json: cleanedOrderSteps.length > 0 ? cleanedOrderSteps : null,
                seo_title: formData.seo_title,
                seo_description: formData.seo_description,
                seo_h1: formData.seo_h1,
                meta_title: formData.seo_title,
                meta_description: formData.seo_description,
                h1_heading: formData.seo_h1
            };

            if (isNew) {
                await api.post('/products/', dataToSave, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                alert('Товар додано!');
            } else {
                await api.patch(`/products/${id}`, dataToSave, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                alert('Товар оновлено!');
            }
            navigate('/admin/products');
        } catch (error) {
            console.error("Failed to save product", error);
            const detail = error.response?.data?.detail;
            const errorMsg = Array.isArray(detail) ? detail.map(d => `${d.loc.join('.')}: ${d.msg}`).join('\n') : (typeof detail === 'string' ? detail : 'Помилка збереження');
            alert(errorMsg);
        }
    };

    if (loading) return (
        <div className="flex items-center justify-center p-20">
            <div className="w-10 h-10 border-4 border-yellow-400 border-t-transparent rounded-full animate-spin"></div>
        </div>
    );

    return (
        <div className="max-w-4xl mx-auto">
            <div className="flex items-center gap-4 mb-6">
                <button onClick={() => navigate('/admin/products')} className="p-2 hover:bg-gray-100 rounded-full">
                    <FiArrowLeft className="w-5 h-5" />
                </button>
                <h1 className="text-2xl font-bold">{isNew ? 'Додавання нового товару' : `Редагування товару: ${formData.name}`}</h1>
            </div>

            <form onSubmit={handleSubmit} className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                {/* Tabs */}
                <div className="flex border-b border-gray-100">
                    <button
                        type="button"
                        onClick={() => setActiveTab('content')}
                        className={`flex-1 flex justify-center py-3 md:py-4 text-[10px] md:text-sm font-bold uppercase tracking-wider text-center ${activeTab === 'content' ? 'bg-gray-50 text-amber-700 border-b-2 border-amber-700' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        Основна інформація
                    </button>
                    <button
                        type="button"
                        onClick={() => setActiveTab('seo')}
                        className={`flex-1 flex justify-center py-3 md:py-4 text-[10px] md:text-sm font-bold uppercase tracking-wider text-center ${activeTab === 'seo' ? 'bg-gray-50 text-amber-700 border-b-2 border-amber-700' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        SEO Налаштування
                    </button>
                </div>

                <div className="p-6 md:p-8">
                    {activeTab === 'content' && (
                        <div className="space-y-6">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
                                <div>
                                    <label className="block text-sm font-bold text-gray-700 mb-2">Назва</label>
                                    <input
                                        type="text"
                                        name="name"
                                        value={formData.name}
                                        onChange={handleChange}
                                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-700 focus:border-transparent"
                                        required
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-bold text-gray-700 mb-2">URL slug (авто з назви якщо пусто)</label>
                                    <input
                                        type="text"
                                        name="slug"
                                        value={formData.slug}
                                        onChange={handleChange}
                                        placeholder="napryklad-drova"
                                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-700 focus:border-transparent"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-bold text-gray-700 mb-2">Ціна (грн)</label>
                                    <input
                                        type="number"
                                        name="price"
                                        value={formData.price}
                                        onChange={handleChange}
                                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-700 focus:border-transparent"
                                        required
                                    />
                                </div>
                            </div>

                            <div className="flex items-center gap-3 p-4 bg-gray-50 border border-gray-200 rounded-lg">
                                <label className="relative inline-flex items-center cursor-pointer">
                                    <input
                                        type="checkbox"
                                        name="is_available"
                                        checked={formData.is_available}
                                        onChange={handleChange}
                                        className="sr-only peer"
                                    />
                                    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-amber-700 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-amber-600"></div>
                                </label>
                                <span className="text-sm font-bold text-gray-700">Відображати на сайті (В наявності)</span>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Опис</label>
                                <textarea
                                    name="description"
                                    rows="4"
                                    value={formData.description}
                                    onChange={handleChange}
                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-700 focus:border-transparent"
                                />
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
                                <div>
                                    <label className="block text-sm font-bold text-gray-700 mb-2">Категорія</label>
                                    <div className="flex gap-2 items-center">
                                        <select
                                            name="category"
                                            value={formData.category}
                                            onChange={handleChange}
                                            className="flex-1 min-w-0 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-700 focus:border-transparent cursor-pointer"
                                        >
                                            <option value="">Оберіть категорію</option>
                                            {categories.map(cat => (
                                                <option key={cat.slug} value={cat.slug}>{cat.name}</option>
                                            ))}
                                        </select>
                                        <button
                                            type="button"
                                            onClick={() => navigate('/admin/categories')}
                                            className="shrink-0 px-3 py-2 text-sm font-bold text-antreme-red border border-red-200 rounded-lg hover:bg-red-50 transition-colors whitespace-nowrap"
                                        >
                                            + Додати
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div className="bg-orange-50 p-6 rounded-xl border border-orange-100 mb-6">
                                <div className="flex justify-between items-center mb-4">
                                    <div>
                                        <h3 className="text-lg font-bold text-gray-900">Варіанти товару (Фасування / Види)</h3>
                                        <p className="text-xs text-gray-500 mt-1">
                                            Якщо товар має декілька видів (наприклад: "В ящиках 2 склм" за 4000 грн, "Рубані" за 2000 грн). Базова ціна вище буде використовуватися як ціна "від".
                                        </p>
                                    </div>
                                    <button
                                        type="button"
                                        onClick={addVariant}
                                        className="px-4 py-2 bg-white border border-orange-300 text-orange-600 rounded-lg text-sm font-bold shadow-sm hover:bg-orange-100 transition-colors"
                                    >
                                        + Додати варіант
                                    </button>
                                </div>

                                {formData.variants.length > 0 ? (
                                    <div className="space-y-3">
                                        {formData.variants.map((variant, index) => (
                                            <div key={index} className="flex items-start gap-4 p-4 bg-white border border-orange-200 rounded-lg shadow-sm">
                                                <div className="flex-1">
                                                    <label className="block text-xs font-bold text-gray-600 mb-1">Назва варіанту</label>
                                                    <input
                                                        type="text"
                                                        value={variant.name}
                                                        onChange={(e) => updateVariant(index, 'name', e.target.value)}
                                                        placeholder='напр: "Рубані"'
                                                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-amber-500 focus:border-transparent text-sm"
                                                    />
                                                </div>
                                                <div className="w-32">
                                                    <label className="block text-xs font-bold text-gray-600 mb-1">Ціна (грн)</label>
                                                    <input
                                                        type="number"
                                                        value={variant.price}
                                                        onChange={(e) => updateVariant(index, 'price', e.target.value)}
                                                        placeholder="2000"
                                                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-amber-500 focus:border-transparent text-sm"
                                                    />
                                                </div>
                                                <button
                                                    type="button"
                                                    onClick={() => removeVariant(index)}
                                                    className="mt-6 px-3 py-2 text-red-500 border border-red-200 hover:bg-red-50 rounded-md transition-colors"
                                                >
                                                    Видалити
                                                </button>
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className="text-center py-6 text-sm text-gray-400 bg-white bg-opacity-50 rounded-lg border border-dashed border-gray-300">
                                        Не додано жодного варіанту. Цей товар не матиме вибору фасування.
                                    </div>
                                )}
                            </div>

                            {/* Accordion Blocks */}
                            <div className="space-y-4 mb-6">
                                {/* Характеристики */}
                                <details className="group bg-white rounded-xl border border-gray-200 overflow-hidden open:ring-2 open:ring-blue-500 open:border-transparent transition-all">
                                    <summary className="flex items-center justify-between p-4 cursor-pointer font-bold text-gray-900 bg-gray-50 group-open:bg-blue-50 group-open:text-blue-700 transition-colors">
                                        <div className="flex items-center gap-2">
                                            <span>📋 Характеристики товару</span>
                                        </div>
                                        <span className="text-xl transform group-open:rotate-180 transition-transform">▾</span>
                                    </summary>
                                    <div className="p-4 md:p-6 border-t border-gray-200">
                                        <div className="flex justify-end mb-4">
                                            <button type="button" onClick={() => setFormData(prev => ({ ...prev, specifications_json: [...(prev.specifications_json || []), { name: '', value: '' }] }))} className="px-3 py-1.5 bg-white border border-blue-300 text-blue-600 rounded-lg text-sm font-bold shadow-sm hover:bg-blue-50">+ Додати характеристику</button>
                                        </div>
                                        <div className="space-y-3">
                                            {(formData.specifications_json || []).map((spec, index) => (
                                                <div key={index} className="flex gap-3 items-start">
                                                    <input type="text" value={spec.name} onChange={(e) => { const n = [...formData.specifications_json]; n[index].name = e.target.value; setFormData(prev => ({ ...prev, specifications_json: n })); }} placeholder="Назва (напр: Порода)" className="w-1/3 px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 text-sm" />
                                                    <input type="text" value={spec.value} onChange={(e) => { const n = [...formData.specifications_json]; n[index].value = e.target.value; setFormData(prev => ({ ...prev, specifications_json: n })); }} placeholder="Значення (напр: Дуб)" className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 text-sm" />
                                                    <button type="button" onClick={() => setFormData(prev => ({ ...prev, specifications_json: prev.specifications_json.filter((_, i) => i !== index) }))} className="p-2 text-red-500 hover:bg-red-50 rounded-md transition-colors" title="Видалити">✕</button>
                                                </div>
                                            ))}
                                            {(!formData.specifications_json || formData.specifications_json.length === 0) && (
                                                <p className="text-center text-sm text-gray-400 py-4">Немає характеристик. На сайті будуть підставлені стандартні (автовизначення).</p>
                                            )}
                                        </div>
                                    </div>
                                </details>
                                {/* Інформація про доставку */}
                                <details className="group bg-white rounded-xl border border-gray-200 overflow-hidden open:ring-2 open:ring-emerald-500 open:border-transparent transition-all">
                                    <summary className="flex items-center justify-between p-4 cursor-pointer font-bold text-gray-900 bg-gray-50 group-open:bg-emerald-50 group-open:text-emerald-700 transition-colors">
                                        <div className="flex items-center gap-2">
                                            <span>🚚 Інформація про доставку</span>
                                        </div>
                                        <span className="text-xl transform group-open:rotate-180 transition-transform">▾</span>
                                    </summary>
                                    <div className="p-4 md:p-6 border-t border-gray-200">
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                            {['location:Локація', 'time:Термін доставки', 'price:Вартість доставки', 'min_order:Мінімальне замовлення', 'fleet:Автопарк', 'special:Спецтехніка'].map((fieldStr) => {
                                                const [key, label] = fieldStr.split(':');
                                                return (
                                                    <div key={key}>
                                                        <label className="block text-xs font-bold text-gray-600 mb-1">{label}</label>
                                                        <input type="text" value={formData.delivery_info_json?.[key] || ''} onChange={(e) => { const n = { ...(formData.delivery_info_json || {}) }; n[key] = e.target.value; setFormData(prev => ({ ...prev, delivery_info_json: n })); }} className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-emerald-500 text-sm" />
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    </div>
                                </details>
                                {/* Як замовити */}
                                <details className="group bg-white rounded-xl border border-gray-200 overflow-hidden open:ring-2 open:ring-purple-500 open:border-transparent transition-all">
                                    <summary className="flex items-center justify-between p-4 cursor-pointer font-bold text-gray-900 bg-gray-50 group-open:bg-purple-50 group-open:text-purple-700 transition-colors">
                                        <div className="flex items-center gap-2">
                                            <span>🛒 Як замовити (кроки)</span>
                                        </div>
                                        <span className="text-xl transform group-open:rotate-180 transition-transform">▾</span>
                                    </summary>
                                    <div className="p-4 md:p-6 border-t border-gray-200">
                                        <div className="flex justify-end mb-4">
                                            <button type="button" onClick={() => setFormData(prev => ({ ...prev, order_steps_json: [...(prev.order_steps_json || []), { step: '' }] }))} className="px-3 py-1.5 bg-white border border-purple-300 text-purple-600 rounded-lg text-sm font-bold shadow-sm hover:bg-purple-50">+ Додати крок</button>
                                        </div>
                                        <div className="space-y-3">
                                            {(formData.order_steps_json || []).map((stepObj, index) => (
                                                <div key={index} className="flex gap-3 items-center">
                                                    <span className="font-bold text-gray-400">{index + 1}.</span>
                                                    <input type="text" value={stepObj.step} onChange={(e) => { const n = [...formData.order_steps_json]; n[index].step = e.target.value; setFormData(prev => ({ ...prev, order_steps_json: n })); }} placeholder="Опис кроку" className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 text-sm" />
                                                    <button type="button" onClick={() => setFormData(prev => ({ ...prev, order_steps_json: prev.order_steps_json.filter((_, i) => i !== index) }))} className="p-2 text-red-500 hover:bg-red-50 rounded-md transition-colors" title="Видалити">✕</button>
                                                </div>
                                            ))}
                                            {(!formData.order_steps_json || formData.order_steps_json.length === 0) && (
                                                <p className="text-center text-sm text-gray-400 py-4">Немає кроків. На сайті будуть стандартні.</p>
                                            )}
                                        </div>
                                    </div>
                                </details>
                                {/* Часті питання FAQ */}
                                <details className="group bg-white rounded-xl border border-gray-200 overflow-hidden open:ring-2 open:ring-orange-500 open:border-transparent transition-all">
                                    <summary className="flex items-center justify-between p-4 cursor-pointer font-bold text-gray-900 bg-gray-50 group-open:bg-orange-50 group-open:text-orange-700 transition-colors">
                                        <div className="flex items-center gap-2">
                                            <span>❓ Часті питання (FAQ)</span>
                                        </div>
                                        <span className="text-xl transform group-open:rotate-180 transition-transform">▾</span>
                                    </summary>
                                    <div className="p-4 md:p-6 border-t border-gray-200">
                                        <div className="flex justify-end mb-4">
                                            <button type="button" onClick={() => setFormData(prev => ({ ...prev, faqs_json: [...(prev.faqs_json || []), { q: '', a: '' }] }))} className="px-3 py-1.5 bg-white border border-orange-300 text-orange-600 rounded-lg text-sm font-bold shadow-sm hover:bg-orange-50">+ Додати питання</button>
                                        </div>
                                        <div className="space-y-4">
                                            {(formData.faqs_json || []).map((faq, index) => (
                                                <div key={index} className="flex gap-3 items-start p-3 bg-gray-50 border border-gray-200 rounded-lg">
                                                    <div className="flex-1 space-y-2">
                                                        <input type="text" value={faq.q} onChange={(e) => { const n = [...formData.faqs_json]; n[index].q = e.target.value; setFormData(prev => ({ ...prev, faqs_json: n })); }} placeholder="Питання" className="w-full px-3 py-2 font-bold border border-gray-300 rounded-md focus:ring-2 focus:ring-orange-500 text-sm" />
                                                        <textarea value={faq.a} onChange={(e) => { const n = [...formData.faqs_json]; n[index].a = e.target.value; setFormData(prev => ({ ...prev, faqs_json: n })); }} placeholder="Відповідь" rows="2" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-orange-500 text-sm" />
                                                    </div>
                                                    <button type="button" onClick={() => setFormData(prev => ({ ...prev, faqs_json: prev.faqs_json.filter((_, i) => i !== index) }))} className="p-2 mt-1 text-red-500 border border-red-200 bg-white hover:bg-red-50 rounded-md transition-colors" title="Видалити">✕</button>
                                                </div>
                                            ))}
                                            {(!formData.faqs_json || formData.faqs_json.length === 0) && (
                                                <p className="text-center text-sm text-gray-400 py-4">Немає питань. На сайті будуть використані стандартні.</p>
                                            )}
                                        </div>
                                    </div>
                                </details>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-3">Зображення товару (до 3 фото)</label>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                    {['image_url', 'image_url_2', 'image_url_3'].map((field, idx) => {
                                        const imgVal = formData[field] || '';
                                        const label = idx === 0 ? 'Головне фото' : `Фото ${idx + 1}`;
                                        return (
                                            <div key={field} className={`p-4 rounded-xl border-2 border-dashed ${idx === 0 ? 'border-amber-300 bg-amber-50/50' : 'border-gray-200 bg-gray-50/50'
                                                }`}>
                                                <p className={`text-xs font-bold mb-2 ${idx === 0 ? 'text-amber-700' : 'text-gray-500'}`}>{label}</p>
                                                {imgVal && (
                                                    <div className="relative mb-3">
                                                        <div className="w-full aspect-square rounded-lg overflow-hidden border border-gray-200">
                                                            <img
                                                                src={imgVal}
                                                                alt={label}
                                                                className="w-full h-full object-cover"
                                                                onError={(e) => { e.target.style.display = 'none'; }}
                                                            />
                                                        </div>
                                                        <button
                                                            type="button"
                                                            onClick={() => setFormData(prev => ({ ...prev, [field]: '' }))}
                                                            className="absolute top-1 right-1 w-7 h-7 flex items-center justify-center bg-red-500 text-white rounded-full text-xs font-bold shadow hover:bg-red-600 transition-colors"
                                                            title="Видалити фото"
                                                        >
                                                            ✕
                                                        </button>
                                                    </div>
                                                )}
                                                <input
                                                    type="file"
                                                    accept="image/*"
                                                    onChange={async (e) => {
                                                        const file = e.target.files[0];
                                                        if (!file) return;
                                                        const uploadData = new FormData();
                                                        uploadData.append('file', file);
                                                        try {
                                                            const response = await api.post('/admin/upload', uploadData, {
                                                                headers: {
                                                                    'Content-Type': 'multipart/form-data',
                                                                    'Authorization': `Bearer ${token}`
                                                                }
                                                            });
                                                            setFormData(prev => ({ ...prev, [field]: response.data.image_url }));
                                                        } catch (error) {
                                                            console.error('Upload failed', error);
                                                            alert('Помилка завантаження файлу');
                                                        }
                                                    }}
                                                    className="block w-full text-xs text-gray-500 file:mr-2 file:py-1.5 file:px-3 file:rounded-full file:border-0 file:text-xs file:font-semibold file:bg-amber-700 file:text-white hover:file:bg-red-700 cursor-pointer"
                                                />
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>
                    )}

                    {activeTab === 'seo' && (
                        <div className="space-y-6">
                            {/* SEO Auto-fill Button */}
                            <div className="flex items-center gap-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                                <button
                                    type="button"
                                    onClick={() => {
                                        const name = formData.name || '';
                                        const slug = formData.slug || '';
                                        const cat = formData.category || 'drova';
                                        if (!name) { alert('Спочатку заповніть назву товару!'); return; }
                                        setFormData(prev => ({
                                            ...prev,
                                            seo_title: prev.seo_title || `Купити ${name.toLowerCase()} з доставкою по Києву — ціна за складометр | КиївДрова`,
                                            seo_description: prev.seo_description || `${name} купити в Києві з доставкою. Чесний складометр, швидка доставка по Києву та області. Типи: колоті, ящик.`,
                                            seo_h1: prev.seo_h1 || `${name} з доставкою по Києву`,
                                            canonical_url: prev.canonical_url || `/catalog/${cat}/${slug}`,
                                            meta_keywords: prev.meta_keywords || 'дрова київ, купити дрова, доставка дров, дрова складометр, дрова для опалення'
                                        }));
                                    }}
                                    className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-bold hover:bg-blue-700 transition-colors whitespace-nowrap"
                                >
                                    🔧 Автозаповнення SEO
                                </button>
                                <p className="text-xs text-blue-700 m-0">
                                    Заповнить порожні SEO поля на основі назви товару. Вже заповнені поля НЕ будуть перезаписані.
                                </p>
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">SEO Title (seo_title)</label>
                                <input
                                    type="text"
                                    name="seo_title"
                                    value={formData.seo_title || ''}
                                    onChange={handleChange}
                                    placeholder="Купити дрова Київ..."
                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                />
                                <p className="text-xs text-gray-500 mt-1">Рекомендована довжина: 50-60 символів.</p>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">SEO Description (seo_description)</label>
                                <textarea
                                    name="seo_description"
                                    rows="3"
                                    value={formData.seo_description || ''}
                                    onChange={handleChange}
                                    placeholder="Якісні дрова на замовлення..."
                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                />
                                <p className="text-xs text-gray-500 mt-1">Рекомендована довжина: 150-160 символів.</p>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">SEO H1 Заголовок (seo_h1)</label>
                                <input
                                    type="text"
                                    name="seo_h1"
                                    value={formData.seo_h1 || ''}
                                    onChange={handleChange}
                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Keywords (Ключові слова)</label>
                                <input
                                    type="text"
                                    name="meta_keywords"
                                    value={formData.meta_keywords}
                                    onChange={handleChange}
                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Canonical URL</label>
                                <input
                                    type="text"
                                    name="canonical_url"
                                    value={formData.canonical_url}
                                    onChange={handleChange}
                                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                />
                            </div>
                        </div>
                    )}
                </div>

                <div className="p-4 md:p-6 bg-gray-50 border-t border-gray-100 flex justify-end">
                    <button
                        type="submit"
                        className="flex items-center justify-center gap-2 w-full md:w-auto bg-orange-500 text-white px-6 py-3 rounded-xl hover:bg-orange-600 transition-all font-bold shadow-md shadow-orange-200 active:scale-95"
                    >
                        <FiSave className="w-5 h-5" />
                        <span>{isNew ? 'Додати товар' : 'Зберегти зміни'}</span>
                    </button>
                </div>
            </form>
        </div>
    );
}
