"""initial_schema_with_timestamps

Revision ID: 44a08f8d1acb
Revises: 
Create Date: 2026-02-26 21:34:08.754433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a08f8d1acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_metadata', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('category_metadata', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'updated_at')
    op.drop_column('pages', 'created_at')
    op.drop_column('category_metadata', 'updated_at')
    op.drop_column('category_metadata', 'created_at')
    # ### end Alembic commands ###
