"""Add name and seo text

Revision ID: 869e47cb71c3
Revises: 44a08f8d1acb
Create Date: 2026-02-27 18:39:33.682132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869e47cb71c3'
down_revision: Union[str, Sequence[str], None] = '44a08f8d1acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('telegram_settings')
    # op.create_index(op.f('ix_cakes_category'), 'cakes', ['category'], unique=False)
    # op.create_index(op.f('ix_cakes_is_available'), 'cakes', ['is_available'], unique=False)
    op.add_column('category_metadata', sa.Column('name', sa.String(), nullable=False, server_default="Unnamed Category"))
    op.add_column('category_metadata', sa.Column('seo_text', sa.String(), nullable=True))
    # op.create_index(op.f('ix_order_items_cake_id'), 'order_items', ['cake_id'], unique=False)
    # op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # op.drop_constraint(None, 'order_items', type_='foreignkey')
    # op.drop_constraint(None, 'order_items', type_='foreignkey')
    # op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'order_items', 'cakes', ['cake_id'], ['id'], ondelete='SET NULL')
    # op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    # op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'cakes', ['cake_id'], ['id'])
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_cake_id'), table_name='order_items')
    op.drop_column('category_metadata', 'seo_text')
    op.drop_column('category_metadata', 'name')
    op.drop_index(op.f('ix_cakes_is_available'), table_name='cakes')
    op.drop_index(op.f('ix_cakes_category'), table_name='cakes')
    # op.create_table('telegram_settings',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('bot_token', sa.VARCHAR(), nullable=True),
    # sa.Column('chat_id_1', sa.VARCHAR(), nullable=True),
    # sa.Column('label_1', sa.VARCHAR(), nullable=True),
    # sa.Column('is_active_1', sa.BOOLEAN(), nullable=True),
    # sa.Column('chat_id_2', sa.VARCHAR(), nullable=True),
    # sa.Column('label_2', sa.VARCHAR(), nullable=True),
    # sa.Column('is_active_2', sa.BOOLEAN(), nullable=True),
    # sa.Column('chat_id_3', sa.VARCHAR(), nullable=True),
    # sa.Column('label_3', sa.VARCHAR(), nullable=True),
    # sa.Column('is_active_3', sa.BOOLEAN(), nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
